// Looks up a photo for every vehicle in vehicles.mjs (the Commons file picked in
// images.mjs, else the Wikipedia article's lead image), then writes:
//   seed/vehicles.json         – data uploaded to the server by the seeding step
//   ../military_vehicles.sql   – full table rebuild for phpMyAdmin
// Run with: node server/seed/build.mjs

import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { VEHICLES } from './vehicles.mjs'
import { IMAGES } from './images.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const UA = 'ArmoredHubSeed/1.0 (student project; https://github.com/arr0nj4y/Military-Vehicles)'

async function fetchImages(titles) {
  const images = {}
  for (let i = 0; i < titles.length; i += 50) {
    const batch = titles.slice(i, i + 50)
    const url =
      'https://en.wikipedia.org/w/api.php?action=query&format=json&redirects=1' +
      '&prop=pageimages&piprop=thumbnail&pithumbsize=800&pilicense=any&titles=' +
      encodeURIComponent(batch.join('|'))
    const res = await fetch(url, { headers: { 'User-Agent': UA } })
    const json = await res.json()
    // Follow normalization + redirects back to the title we asked for.
    const alias = {}
    for (const n of json.query.normalized || []) alias[n.to] = n.from
    for (const r of json.query.redirects || []) alias[r.to] = alias[r.from] || r.from
    for (const page of Object.values(json.query.pages)) {
      const asked = alias[page.title] || page.title
      if (page.thumbnail) images[asked] = page.thumbnail.source
    }
  }
  return images
}

// Direct Wikimedia Commons files ("File:..."), 50 per request to stay under rate limits.
async function fetchCommonsFiles(titles) {
  const images = {}
  for (let i = 0; i < titles.length; i += 50) {
    const batch = titles.slice(i, i + 50)
    const url =
      'https://commons.wikimedia.org/w/api.php?action=query&format=json' +
      '&prop=imageinfo&iiprop=url&iiurlwidth=800&titles=' + encodeURIComponent(batch.join('|'))
    const res = await fetch(url, { headers: { 'User-Agent': UA } })
    const json = await res.json()
    const alias = {}
    for (const n of json.query.normalized || []) alias[n.to] = n.from
    for (const page of Object.values(json.query.pages)) {
      if (page.imageinfo) images[alias[page.title] || page.title] = page.imageinfo[0].thumburl
    }
  }
  return images
}

// A hand-picked Commons photo from images.mjs wins over the article's lead image.
const photoTitle = (v) => IMAGES[v.name] || v.wiki
const titles = [...new Set(VEHICLES.map(photoTitle))]
const images = {
  ...(await fetchImages(titles.filter((t) => !t.startsWith('File:')))),
  ...(await fetchCommonsFiles(titles.filter((t) => t.startsWith('File:')))),
}

const rows = VEHICLES.map(({ wiki, ...v }) => ({ ...v, image_url: images[photoTitle({ ...v, wiki })] || '' }))
const missing = VEHICLES.filter((v) => !images[photoTitle(v)]).map((v) => v.name)

writeFileSync(join(here, 'vehicles.json'), JSON.stringify(rows, null, 2))

const q = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "''") + "'"
const cols = ['name', 'category', 'country', 'era', 'image_url', 'top_speed', 'range', 'crew', 'weight', 'armament', 'description', 'admin_note']
const sql = `-- ArmoredHub: military_vehicles table + seed data (${rows.length} vehicles).
-- Generated by server/seed/build.mjs — edit seed/vehicles.mjs, not this file.
-- Import in phpMyAdmin (database arrjam10_military_vehicle) to recreate from scratch.

CREATE TABLE IF NOT EXISTS military_vehicles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NOT NULL DEFAULT '',
  country VARCHAR(100) NOT NULL DEFAULT '',
  era VARCHAR(50) NOT NULL DEFAULT '',
  image_url TEXT,
  top_speed VARCHAR(50) NOT NULL DEFAULT '',
  \`range\` VARCHAR(50) NOT NULL DEFAULT '',
  crew VARCHAR(50) NOT NULL DEFAULT '',
  weight VARCHAR(50) NOT NULL DEFAULT '',
  armament TEXT,
  description TEXT,
  admin_note TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO military_vehicles
  (${cols.map((c) => '`' + c + '`').join(', ')})
VALUES
${rows.map((r) => '  (' + cols.map((c) => q(r[c])).join(', ') + ')').join(',\n')};
`
writeFileSync(join(here, '..', 'military_vehicles.sql'), sql)

console.log(`${rows.length} vehicles, ${rows.length - missing.length} with photos`)
if (missing.length) console.log('No photo:', missing.join(', '))
