// Seed catalog for the military_vehicles table.
// `wiki` is the English Wikipedia article used to look up a photo (build.mjs),
// or a Wikimedia Commons "File:..." name when the article's photo is missing or wrong.
// Specs are approximate public figures; unknown values are left blank so the
// app simply hides that spec.

const v = (name, category, country, era, top_speed, range, crew, weight, armament, description, wiki, admin_note = '') => ({
  name, category, country, era, top_speed, range, crew, weight, armament, description, wiki, admin_note,
})

export const VEHICLES = [
  // ---- Original catalog ----
  v('M1A2 Abrams', 'Main Battle Tank', 'USA', 'Modern', '67 km/h', '426 km', '4', '62 tons',
    '120mm M256 smoothbore gun, 2x 7.62mm, 1x 12.7mm',
    'The M1A2 Abrams is the main battle tank of the United States Army, featuring advanced composite armor, a 120mm smoothbore cannon, and a gas-turbine engine.',
    'M1 Abrams', 'Export variant restrictions apply. Verify FMS documentation.'),
  v('Leopard 2A7', 'Main Battle Tank', 'Germany', 'Modern', '68 km/h', '450 km', '4', '67 tons',
    '120mm Rheinmetall L/55 smoothbore gun, 2x 7.62mm MG3',
    'The Leopard 2A7 is a third-generation German main battle tank, widely regarded for its firepower, protection, and mobility across NATO forces.',
    'Leopard 2'),
  v('T-90M Proryv', 'Main Battle Tank', 'Russia', 'Modern', '60 km/h', '550 km', '3', '48 tons',
    '125mm 2A46M-5 smoothbore gun, Kord 12.7mm, PKTM 7.62mm',
    'The T-90M is a modernized Russian main battle tank with the Relikt explosive reactive armor package and an upgraded fire-control system.',
    'T-90'),
  v('M2A3 Bradley', 'Infantry Fighting Vehicle', 'USA', 'Cold War', '66 km/h', '400 km', '3 + 6 troops', '27 tons',
    '25mm M242 Bushmaster, TOW missile launcher, 7.62mm coax',
    'The M2 Bradley is a tracked infantry fighting vehicle that transports a squad while providing fire support with its autocannon and anti-tank missiles.',
    'M2 Bradley'),
  v('BMP-3', 'Infantry Fighting Vehicle', 'Russia', 'Cold War', '70 km/h', '600 km', '3 + 7 troops', '18.7 tons',
    '100mm 2A70 gun, 30mm 2A72 autocannon, 3x 7.62mm PKT',
    'The BMP-3 is a Soviet-designed amphibious infantry fighting vehicle with a uniquely heavy mixed-caliber armament package for its class.',
    'BMP-3'),
  v('M1126 Stryker', 'Armored Personnel Carrier', 'USA', 'Modern', '100 km/h', '500 km', '2 + 9 troops', '18 tons',
    '12.7mm M2 or 40mm Mk19 grenade launcher (RWS)',
    'The Stryker is an eight-wheeled armored personnel carrier providing rapid, protected mobility for infantry squads on the modern battlefield.',
    'Stryker'),
  v('M109A7 Paladin', 'Self-Propelled Artillery', 'USA', 'Modern', '61 km/h', '300 km', '4', '36 tons',
    '155mm M284 howitzer, 12.7mm M2 machine gun',
    'The M109A7 Paladin is a self-propelled 155mm howitzer providing indirect fire support with improved survivability and automated loading.',
    'M109 howitzer'),
  v('Tiger I', 'Heavy Tank', 'Germany', 'WWII', '45 km/h', '195 km', '5', '57 tons',
    '88mm KwK 36 L/56 gun, 2x 7.92mm MG 34',
    'The Tiger I was a German heavy tank of World War II, renowned for its powerful 88mm gun and thick frontal armor that dominated early engagements.',
    'Tiger I', 'Historical reference entry — not in active service.'),

  // ---- Main battle tanks ----
  v('Challenger 2', 'Main Battle Tank', 'United Kingdom', 'Modern', '59 km/h', '550 km', '4', '62.5 tons',
    '120mm L30A1 rifled gun, 7.62mm L94A1 chain gun, 7.62mm L37A2 MG',
    'The Challenger 2 is the British Army\'s main battle tank, known for its Dorchester armour and its service in the Balkans and Iraq.',
    'Challenger 2'),
  v('Leclerc', 'Main Battle Tank', 'France', 'Modern', '71 km/h', '550 km', '3', '57 tons',
    '120mm CN120-26/52 smoothbore gun with autoloader, 12.7mm M2HB coax, 7.62mm MG',
    'The Leclerc is France\'s main battle tank, featuring an autoloader that allows a three-person crew and a high-performance hyperbar diesel engine.',
    'Leclerc tank'),
  v('Merkava Mk 4', 'Main Battle Tank', 'Israel', 'Modern', '64 km/h', '500 km', '4', '65 tons',
    '120mm MG253 smoothbore gun, 60mm mortar, 3x 7.62mm MG',
    'The Merkava Mk 4 places its engine at the front for extra crew protection and has a rear hatch that can carry infantry or casualties. It is fitted with the Trophy active protection system.',
    'Merkava'),
  v('K2 Black Panther', 'Main Battle Tank', 'South Korea', 'Modern', '70 km/h', '450 km', '3', '55 tons',
    '120mm CN08 L/55 smoothbore gun with autoloader, 12.7mm K6, 7.62mm coax',
    'The K2 Black Panther is one of the most advanced tanks in service, with hydropneumatic suspension that lets it kneel and tilt to aim over terrain.',
    'K2 Black Panther'),
  v('Type 10', 'Main Battle Tank', 'Japan', 'Modern', '70 km/h', '440 km', '3', '44 tons',
    '120mm L/44 smoothbore gun with autoloader, 12.7mm M2, 7.62mm coax',
    'The Type 10 is a lightweight Japanese main battle tank with modular ceramic armour and a C4I network system, designed for mobility on Japan\'s roads and bridges.',
    'Type 10 tank'),
  v('Type 99A', 'Main Battle Tank', 'China', 'Modern', '70 km/h', '450 km', '3', '55 tons',
    '125mm ZPT-98 smoothbore gun with autoloader, 12.7mm QJC-88, 7.62mm coax',
    'The Type 99A is the most capable main battle tank of the Chinese People\'s Liberation Army, fitted with composite and reactive armour and a laser warning system.',
    'Type 99 tank'),
  v('T-14 Armata', 'Main Battle Tank', 'Russia', 'Modern', '80 km/h', '500 km', '3', '55 tons',
    '125mm 2A82-1M smoothbore gun, 12.7mm Kord RWS, 7.62mm PKTM',
    'The T-14 Armata is a Russian tank with an unmanned turret; its crew of three sits in an armoured capsule in the hull. Only a small number have been produced.',
    'T-14 Armata'),
  v('T-72B3', 'Main Battle Tank', 'Russia', 'Cold War', '60 km/h', '460 km', '3', '46 tons',
    '125mm 2A46M-5 smoothbore gun, 12.7mm Kord, 7.62mm PKT',
    'The T-72 is one of the most widely produced tanks in history. The B3 upgrade adds modern thermal sights and a better fire-control system to the 1970s Soviet design.',
    'T-72'),
  v('T-80BV', 'Main Battle Tank', 'Soviet Union', 'Cold War', '70 km/h', '335 km', '3', '42.5 tons',
    '125mm 2A46-2 smoothbore gun, 12.7mm NSVT, 7.62mm PKT',
    'The T-80 was the first production tank to use a gas-turbine engine as its main powerplant, giving it high speed at the cost of heavy fuel consumption.',
    'T-80'),
  v('T-55', 'Main Battle Tank', 'Soviet Union', 'Cold War', '50 km/h', '500 km', '4', '36 tons',
    '100mm D-10T2S rifled gun, 12.7mm DShK, 7.62mm SGMT',
    'The T-54/T-55 series is the most-produced tank family in history, with tens of thousands built and service in more than 50 countries.',
    'T-54/T-55'),
  v('M60A3 Patton', 'Main Battle Tank', 'USA', 'Cold War', '48 km/h', '480 km', '4', '52.6 tons',
    '105mm M68 rifled gun, 12.7mm M85, 7.62mm M240',
    'The M60 was the US Army\'s main battle tank through most of the Cold War; the A3 variant added a laser rangefinder and thermal sights.',
    'M60 tank'),
  v('Leopard 1A5', 'Main Battle Tank', 'West Germany', 'Cold War', '65 km/h', '600 km', '4', '42.4 tons',
    '105mm L7A3 rifled gun, 2x 7.62mm MG3',
    'The Leopard 1 put mobility ahead of armour and became one of the most successful Western tanks of the Cold War, exported across Europe and beyond.',
    'Leopard 1'),
  v('Chieftain Mk 10', 'Main Battle Tank', 'United Kingdom', 'Cold War', '48 km/h', '500 km', '4', '55 tons',
    '120mm L11A5 rifled gun, 12.7mm ranging MG, 2x 7.62mm MG',
    'The Chieftain was the most heavily armed and armoured tank in NATO when it entered service in the 1960s, and it introduced a reclined driver position.',
    'Chieftain (tank)'),
  v('Centurion', 'Main Battle Tank', 'United Kingdom', 'Cold War', '35 km/h', '190 km', '4', '51 tons',
    '105mm L7 rifled gun (later marks), 7.62mm coax',
    'The Centurion was one of the most successful post-war tank designs, serving in conflicts from Korea to the Middle East for more than 50 years.',
    'Centurion (tank)'),
  v('Arjun Mk 1A', 'Main Battle Tank', 'India', 'Modern', '58 km/h', '450 km', '4', '68 tons',
    '120mm rifled gun, 12.7mm AA MG, 7.62mm coax',
    'The Arjun is India\'s domestically developed main battle tank; the Mk 1A adds dozens of upgrades to firepower, mobility, and protection.',
    'Arjun (tank)'),
  v('Altay', 'Main Battle Tank', 'Turkey', 'Modern', '65 km/h', '450 km', '4', '65 tons',
    '120mm L/55 smoothbore gun, 12.7mm RWS, 7.62mm coax',
    'The Altay is Turkey\'s new-generation main battle tank, developed with South Korean assistance and based on K2 technology.',
    'Altay (tank)'),
  v('C1 Ariete', 'Main Battle Tank', 'Italy', 'Modern', '65 km/h', '550 km', '4', '54 tons',
    '120mm OTO Melara smoothbore gun, 2x 7.62mm MG',
    'The Ariete is the Italian Army\'s main battle tank, built by the Iveco–OTO Melara consortium and in service since 1995.',
    'C1 Ariete'),
  v('Stridsvagn 122', 'Main Battle Tank', 'Sweden', 'Modern', '68 km/h', '550 km', '4', '62 tons',
    '120mm L/44 smoothbore gun, 2x 7.62mm MG',
    'The Stridsvagn 122 is a Swedish Leopard 2 variant with extra armour and a command-and-control system tailored to the Swedish Army.',
    'Stridsvagn 122'),
  v('PT-91 Twardy', 'Main Battle Tank', 'Poland', 'Modern', '60 km/h', '650 km', '3', '45.3 tons',
    '125mm 2A46 smoothbore gun, 12.7mm NSVT, 7.62mm PKT',
    'The PT-91 Twardy is a Polish development of the T-72M1, adding ERAWA explosive reactive armour and a modernised fire-control system.',
    'PT-91 Twardy'),
  v('T-84 Oplot-M', 'Main Battle Tank', 'Ukraine', 'Modern', '70 km/h', '500 km', '3', '51 tons',
    '125mm KBA-3 smoothbore gun, 12.7mm KT-12.7, 7.62mm coax',
    'The Oplot-M is Ukraine\'s most advanced tank, developed from the T-80UD with a welded turret, Duplet reactive armour, and a diesel engine.',
    'T-84'),
  v('Al-Khalid', 'Main Battle Tank', 'Pakistan', 'Modern', '70 km/h', '450 km', '3', '48 tons',
    '125mm smoothbore gun with autoloader, 12.7mm AA MG, 7.62mm coax',
    'The Al-Khalid was jointly developed by Pakistan and China and serves as a mainstay of the Pakistan Army\'s armoured corps.',
    'Al-Khalid tank'),

  // ---- WWII and Cold War medium, heavy and light tanks ----
  v('M4A3E8 Sherman', 'Medium Tank', 'USA', 'WWII', '48 km/h', '160 km', '5', '33.7 tons',
    '76mm M1 gun, 12.7mm M2, 2x 7.62mm M1919',
    'The M4 Sherman was the most widely used Allied tank of WWII. The "Easy Eight" variant added a longer 76mm gun and horizontal volute spring suspension.',
    'M4 Sherman'),
  v('T-34-85', 'Medium Tank', 'Soviet Union', 'WWII', '55 km/h', '300 km', '5', '32 tons',
    '85mm ZiS-S-53 gun, 2x 7.62mm DT',
    'The T-34 combined sloped armour, a powerful gun, and ease of production. The T-34-85 up-gunned version became the backbone of Soviet armoured forces in 1944–45.',
    'T-34-85'),
  v('Panther Ausf. G', 'Medium Tank', 'Germany', 'WWII', '46 km/h', '200 km', '5', '44.8 tons',
    '75mm KwK 42 L/70 gun, 2x 7.92mm MG 34',
    'The Panther was Germany\'s answer to the T-34, pairing a high-velocity 75mm gun with thick sloped frontal armour.',
    'Panther tank'),
  v('Panzer IV Ausf. H', 'Medium Tank', 'Germany', 'WWII', '38 km/h', '200 km', '5', '25 tons',
    '75mm KwK 40 L/48 gun, 2x 7.92mm MG 34',
    'The Panzer IV was the only German tank to stay in production for the whole war, adapting from infantry support to a capable anti-tank role.',
    'Panzer IV'),
  v('Cromwell', 'Medium Tank', 'United Kingdom', 'WWII', '64 km/h', '270 km', '5', '27.9 tons',
    '75mm OQF gun, 2x 7.92mm Besa MG',
    'The Cromwell was one of the fastest tanks of WWII thanks to its Rolls-Royce Meteor engine, derived from the Merlin aero engine.',
    'Cromwell tank'),
  v('Type 97 Chi-Ha', 'Medium Tank', 'Japan', 'WWII', '38 km/h', '210 km', '4', '15 tons',
    '57mm Type 97 gun, 2x 7.7mm Type 97 MG',
    'The Type 97 Chi-Ha was the most widely produced Japanese medium tank of WWII, used across China, the Pacific, and Southeast Asia.',
    'Type 97 Chi-Ha'),
  v('Tiger II', 'Heavy Tank', 'Germany', 'WWII', '41.5 km/h', '170 km', '5', '69.8 tons',
    '88mm KwK 43 L/71 gun, 2x 7.92mm MG 34',
    'The Tiger II ("King Tiger") combined the long 88mm gun with heavily sloped armour, but its weight made it unreliable and fuel-hungry.',
    'Tiger II'),
  v('IS-2', 'Heavy Tank', 'Soviet Union', 'WWII', '37 km/h', '240 km', '4', '46 tons',
    '122mm D-25T gun, 12.7mm DShK, 3x 7.62mm DT',
    'The IS-2 was a Soviet breakthrough tank whose 122mm gun was designed to knock out fortifications and German heavy tanks alike.',
    'IS-2'),
  v('KV-1', 'Heavy Tank', 'Soviet Union', 'WWII', '35 km/h', '250 km', '5', '45 tons',
    '76.2mm ZiS-5 gun, 3x 7.62mm DT',
    'The KV-1 was nearly immune to German anti-tank guns in 1941, and a single KV could hold up entire columns during the early months of Operation Barbarossa.',
    'KV-1'),
  v('Churchill Mk VII', 'Heavy Tank', 'United Kingdom', 'WWII', '21 km/h', '140 km', '5', '41 tons',
    '75mm OQF gun, 2x 7.92mm Besa MG',
    'The Churchill was a heavily armoured British infantry tank that could climb steep terrain, and it formed the basis of many specialist engineering vehicles.',
    'Churchill tank'),
  v('M26 Pershing', 'Heavy Tank', 'USA', 'WWII', '40 km/h', '160 km', '5', '41.9 tons',
    '90mm M3 gun, 12.7mm M2, 2x 7.62mm M1919',
    'The M26 Pershing arrived in the last months of WWII and became the basis for the US Patton tank series.',
    'M26 Pershing'),
  v('M24 Chaffee', 'Light Tank', 'USA', 'WWII', '56 km/h', '160 km', '5', '18.4 tons',
    '75mm M6 gun, 12.7mm M2, 2x 7.62mm M1919',
    'The M24 Chaffee replaced the M3/M5 Stuart, adding a 75mm gun while keeping the speed a reconnaissance tank needs.',
    'M24 Chaffee'),
  v('M3 Stuart', 'Light Tank', 'USA', 'WWII', '58 km/h', '120 km', '4', '14.7 tons',
    '37mm M6 gun, 3x 7.62mm M1919',
    'The M3 Stuart was a fast, reliable light tank supplied to Allied forces around the world. British crews nicknamed it the "Honey".',
    'M3 Stuart'),
  v('PT-76', 'Light Tank', 'Soviet Union', 'Cold War', '44 km/h', '370 km', '3', '14.6 tons',
    '76.2mm D-56T gun, 7.62mm SGMT',
    'The PT-76 is an amphibious light tank that swims with water jets. It saw action from Vietnam to the Indo-Pakistani wars.',
    'PT-76'),
  v('M551 Sheridan', 'Light Tank', 'USA', 'Cold War', '70 km/h', '560 km', '4', '15.2 tons',
    '152mm M81 gun/launcher (MGM-51 Shillelagh), 12.7mm M2, 7.62mm coax',
    'The M551 Sheridan was an air-droppable light tank whose 152mm gun could fire both conventional shells and guided missiles.',
    'M551 Sheridan'),
  v('FV101 Scorpion', 'Light Tank', 'United Kingdom', 'Cold War', '72 km/h', '756 km', '3', '8 tons',
    '76mm L23A1 gun, 7.62mm L43A1 coax',
    'The Scorpion holds the record as the fastest production tank. It was light enough to be airlifted and used aluminium armour.',
    'FV101 Scorpion'),
  v('ZTQ-15', 'Light Tank', 'China', 'Modern', '70 km/h', '450 km', '3', '36 tons',
    '105mm rifled gun, 12.7mm HMG, 7.62mm coax',
    'The ZTQ-15 (Type 15) light tank was designed for high-altitude and rugged terrain such as the Tibetan Plateau, where heavy tanks struggle.',
    'Type 15 tank'),
  v('M10 Booker', 'Light Tank', 'USA', 'Modern', '64 km/h', '', '4', '42 tons',
    '105mm M35 rifled gun, 12.7mm M2, 7.62mm coax',
    'The M10 Booker was a US Army infantry-support vehicle developed under the Mobile Protected Firepower program. The Army cancelled it in 2025.',
    'M10 Booker'),

  // ---- Tank destroyers ----
  v('Jagdpanther', 'Tank Destroyer', 'Germany', 'WWII', '46 km/h', '160 km', '5', '45.5 tons',
    '88mm Pak 43/3 L/71 gun, 7.92mm MG 34',
    'The Jagdpanther mounted the Tiger II\'s 88mm gun on a Panther chassis and is often regarded as one of the best tank destroyers of the war.',
    'Jagdpanther'),
  v('StuG III Ausf. G', 'Tank Destroyer', 'Germany', 'WWII', '40 km/h', '155 km', '4', '23.9 tons',
    '75mm StuK 40 L/48 gun, 7.92mm MG 34',
    'The StuG III was Germany\'s most-produced fully tracked armoured fighting vehicle of WWII. Its low profile made it an effective assault gun and tank hunter.',
    'Sturmgeschütz III'),
  v('M18 Hellcat', 'Tank Destroyer', 'USA', 'WWII', '80 km/h', '169 km', '5', '17.7 tons',
    '76mm M1A1 gun, 12.7mm M2',
    'The M18 Hellcat was the fastest tracked armoured vehicle of WWII, sacrificing armour for speed and ambush tactics.',
    'M18 Hellcat'),
  v('SU-100', 'Tank Destroyer', 'Soviet Union', 'WWII', '48 km/h', '310 km', '4', '31.6 tons',
    '100mm D-10S gun',
    'The SU-100 put a powerful 100mm gun on the T-34 chassis and remained in service with some armies decades after WWII.',
    'SU-100'),
  v('B1 Centauro', 'Tank Destroyer', 'Italy', 'Modern', '108 km/h', '800 km', '4', '25 tons',
    '105mm L/52 rifled gun, 2x 7.62mm MG',
    'The Centauro is an eight-wheeled tank destroyer that pioneered the concept of a wheeled vehicle carrying a tank-calibre gun.',
    'B1 Centauro'),
  v('2S25 Sprut-SD', 'Tank Destroyer', 'Russia', 'Modern', '70 km/h', '500 km', '3', '18 tons',
    '125mm 2A75 smoothbore gun, 7.62mm PKT',
    'The Sprut-SD is an amphibious, air-droppable tank destroyer for Russian airborne forces, armed with a full-size 125mm tank gun.',
    '2S25 Sprut-SD'),

  // ---- Infantry fighting vehicles ----
  v('CV90', 'Infantry Fighting Vehicle', 'Sweden', 'Modern', '70 km/h', '600 km', '3 + 8 troops', '35 tons',
    '40mm Bofors L/70 autocannon (CV9040), 7.62mm coax',
    'The CV90 family was designed for Nordic winters and is now operated by many European armies in a wide range of variants.',
    'CV90'),
  v('Puma', 'Infantry Fighting Vehicle', 'Germany', 'Modern', '70 km/h', '600 km', '3 + 6 troops', '43 tons',
    '30mm MK30-2/ABM autocannon, 5.56mm MG4, Spike-LR ATGM',
    'The Puma is one of the most heavily protected infantry fighting vehicles in the world, with modular armour packages and a remote-controlled turret.',
    'Puma (IFV)'),
  v('Marder 1A3', 'Infantry Fighting Vehicle', 'West Germany', 'Cold War', '65 km/h', '520 km', '3 + 6 troops', '35 tons',
    '20mm Rh 202 autocannon, 7.62mm MG3, MILAN ATGM',
    'The Marder was the first infantry fighting vehicle fielded by a NATO army and served the Bundeswehr for five decades.',
    'Marder (IFV)'),
  v('FV510 Warrior', 'Infantry Fighting Vehicle', 'United Kingdom', 'Cold War', '75 km/h', '660 km', '3 + 7 troops', '25.4 tons',
    '30mm L21A1 RARDEN cannon, 7.62mm L94A1 chain gun',
    'The Warrior has been the British Army\'s tracked infantry fighting vehicle since 1988 and saw extensive service in the Gulf, the Balkans, and Iraq.',
    'Warrior tracked armoured vehicle'),
  v('BMP-1', 'Infantry Fighting Vehicle', 'Soviet Union', 'Cold War', '65 km/h', '600 km', '3 + 8 troops', '13.2 tons',
    '73mm 2A28 Grom gun, 9M14 Malyutka ATGM, 7.62mm PKT',
    'The BMP-1 was the world\'s first mass-produced infantry fighting vehicle. It let troops fight from inside the vehicle under armour.',
    'BMP-1'),
  v('BMP-2', 'Infantry Fighting Vehicle', 'Soviet Union', 'Cold War', '65 km/h', '600 km', '3 + 7 troops', '14 tons',
    '30mm 2A42 autocannon, 9M113 Konkurs ATGM, 7.62mm PKT',
    'The BMP-2 replaced its predecessor\'s low-pressure gun with a rapid-fire 30mm autocannon that can engage helicopters and light vehicles.',
    'BMP-2'),
  v('VBCI', 'Infantry Fighting Vehicle', 'France', 'Modern', '100 km/h', '750 km', '2 + 9 troops', '28 tons',
    '25mm M811 autocannon, 7.62mm coax',
    'The VBCI is a French eight-wheeled infantry fighting vehicle built for strategic mobility, and it has been deployed to Mali and Lebanon.',
    'VBCI'),
  v('K21', 'Infantry Fighting Vehicle', 'South Korea', 'Modern', '70 km/h', '500 km', '3 + 9 troops', '25 tons',
    '40mm K40 autocannon, 7.62mm coax, Hyungung ATGM',
    'The K21 uses a composite hull to stay light enough to swim while carrying a powerful 40mm gun.',
    'File:2014.4.1 육군 수도기계화보병사단 K-21 장갑차 사격집중훈련 Republic of Korea Army (13592630584).jpg'),
  v('ZBD-04A', 'Infantry Fighting Vehicle', 'China', 'Modern', '65 km/h', '500 km', '3 + 7 troops', '24 tons',
    '100mm gun/launcher, 30mm autocannon, 7.62mm coax',
    'The ZBD-04 is a Chinese amphibious infantry fighting vehicle whose turret layout is inspired by the BMP-3.',
    'ZBD-04'),
  v('BMD-4M', 'Infantry Fighting Vehicle', 'Russia', 'Modern', '70 km/h', '500 km', '3 + 5 troops', '13.6 tons',
    '100mm 2A70 gun, 30mm 2A72 autocannon, 7.62mm PKT',
    'The BMD-4M is an air-droppable infantry fighting vehicle for Russian airborne troops, sharing the BMP-3\'s heavy turret.',
    'BMD-4'),
  v('Lynx KF41', 'Infantry Fighting Vehicle', 'Germany', 'Modern', '70 km/h', '500 km', '3 + 8 troops', '44 tons',
    '30mm or 35mm Wotan autocannon, 7.62mm coax, Spike-LR ATGM',
    'The Rheinmetall Lynx is a modular infantry fighting vehicle chosen by Hungary and Italy, built to be reconfigured for different missions.',
    'Lynx (Rheinmetall armoured fighting vehicle)'),

  // ---- Armored personnel carriers ----
  v('M113', 'Armored Personnel Carrier', 'USA', 'Cold War', '67 km/h', '480 km', '2 + 11 troops', '12.3 tons',
    '12.7mm M2 Browning',
    'The M113 is the most widely used armoured fighting vehicle family ever, with more than 80,000 built in dozens of variants. The Philippine Army also operates it.',
    'M113 armored personnel carrier'),
  v('BTR-80', 'Armored Personnel Carrier', 'Soviet Union', 'Cold War', '80 km/h', '600 km', '3 + 7 troops', '13.6 tons',
    '14.5mm KPVT, 7.62mm PKT',
    'The BTR-80 is an eight-wheeled amphibious armoured personnel carrier that serves widely across the former Soviet Union and beyond.',
    'File:BTR-80 swimming.jpg'),
  v('BTR-82A', 'Armored Personnel Carrier', 'Russia', 'Modern', '80 km/h', '600 km', '3 + 7 troops', '15.4 tons',
    '30mm 2A72 autocannon, 7.62mm PKTM',
    'The BTR-82A modernises the BTR-80 with a 30mm autocannon, spall liners, and improved night sights.',
    'BTR-82A'),
  v('Boxer', 'Armored Personnel Carrier', 'Germany', 'Modern', '103 km/h', '1,050 km', '3 + 8 troops', '36.5 tons',
    '12.7mm HMG or 40mm GMW grenade launcher (RWS)',
    'The Boxer uses swappable mission modules on a common 8x8 drive chassis, so one platform can serve as a troop carrier, ambulance, or command post.',
    'Boxer (armoured fighting vehicle)'),
  v('Patria AMV', 'Armored Personnel Carrier', 'Finland', 'Modern', '100 km/h', '800 km', '2 + 10 troops', '26 tons',
    '12.7mm RWS or 30mm turret',
    'The Patria AMV is a modular Finnish 8x8 vehicle known for protection and off-road mobility, operated by more than ten countries.',
    'Patria AMV'),
  v('Namer', 'Armored Personnel Carrier', 'Israel', 'Modern', '60 km/h', '500 km', '3 + 9 troops', '60 tons',
    '12.7mm M2 or 30mm RWS, 7.62mm MG',
    'The Namer is built on a Merkava tank chassis, which makes it one of the most heavily armoured troop carriers in the world.',
    'Namer'),
  v('FV432', 'Armored Personnel Carrier', 'United Kingdom', 'Cold War', '52 km/h', '580 km', '2 + 10 troops', '15.3 tons',
    '7.62mm L7 GPMG',
    'The FV432 has carried British infantry since the 1960s and remains in use as a mortar carrier, ambulance, and command vehicle.',
    'FV432'),
  v('TPz Fuchs', 'Armored Personnel Carrier', 'West Germany', 'Cold War', '105 km/h', '800 km', '2 + 10 troops', '17 tons',
    '7.62mm MG3',
    'The Fuchs is an amphibious 6x6 transport best known in NBC reconnaissance roles, detecting nuclear, biological, and chemical hazards.',
    'TPz Fuchs'),
  v('VAB', 'Armored Personnel Carrier', 'France', 'Cold War', '92 km/h', '1,000 km', '2 + 10 troops', '13.8 tons',
    '12.7mm M2 or 7.62mm MG',
    'The VAB (Véhicule de l\'Avant Blindé) was the French Army\'s standard wheeled troop carrier for four decades.',
    'Véhicule de l\'Avant Blindé'),
  v('Sd.Kfz. 251', 'Armored Personnel Carrier', 'Germany', 'WWII', '52.5 km/h', '300 km', '2 + 10 troops', '9 tons',
    '2x 7.92mm MG 34/42',
    'The Sd.Kfz. 251 half-track carried German panzergrenadiers so they could keep pace with the tanks, and it was built in more than 20 variants.',
    'Sd.Kfz. 251'),
  v('M3 Half-track', 'Armored Personnel Carrier', 'USA', 'WWII', '72 km/h', '320 km', '3 + 10 troops', '9.1 tons',
    '12.7mm M2, 7.62mm M1919',
    'The M3 Half-track was the main American armoured troop carrier of WWII and was supplied in large numbers to Allied forces.',
    'M3 half-track'),
  v('Universal Carrier', 'Armored Personnel Carrier', 'United Kingdom', 'WWII', '48 km/h', '250 km', '2–5', '3.75 tons',
    '.303 Bren LMG or Boys anti-tank rifle',
    'The Universal Carrier (Bren Carrier) is the most-produced armoured fighting vehicle in history, with around 113,000 built.',
    'Universal Carrier'),
  v('MaxxPro MRAP', 'Armored Personnel Carrier', 'USA', 'Modern', '105 km/h', '600 km', '2 + 6 troops', '14 tons',
    '12.7mm M2 or 40mm Mk19 (CROWS)',
    'The MaxxPro is a mine-resistant ambush-protected vehicle with a V-shaped hull that deflects blasts from roadside bombs.',
    'International MaxxPro'),
  v('Bushmaster PMV', 'Armored Personnel Carrier', 'Australia', 'Modern', '100 km/h', '800 km', '1 + 9 troops', '15 tons',
    '7.62mm or 12.7mm MG',
    'The Bushmaster is an Australian protected mobility vehicle credited with saving many lives in Afghanistan, and it has been exported to several armies.',
    'Bushmaster Protected Mobility Vehicle'),

  // ---- Self-propelled and rocket artillery ----
  v('PzH 2000', 'Self-Propelled Artillery', 'Germany', 'Modern', '60 km/h', '420 km', '5', '55.8 tons',
    '155mm L/52 howitzer, 7.62mm MG3',
    'The Panzerhaubitze 2000 can fire three rounds in under ten seconds and put several shells on one target at the same moment (MRSI).',
    'Panzerhaubitze 2000'),
  v('K9 Thunder', 'Self-Propelled Artillery', 'South Korea', 'Modern', '67 km/h', '360 km', '5', '47 tons',
    '155mm L/52 howitzer, 12.7mm K6',
    'The K9 Thunder is the world\'s best-selling self-propelled howitzer, operated by more than ten countries.',
    'K9 Thunder'),
  v('CAESAR', 'Self-Propelled Artillery', 'France', 'Modern', '100 km/h', '600 km', '5', '17.7 tons',
    '155mm L/52 truck-mounted howitzer',
    'CAESAR mounts a 155mm howitzer on a 6x6 truck, so it can fire and move away within minutes and can be airlifted by a C-130.',
    'CAESAR self-propelled howitzer'),
  v('2S19 Msta-S', 'Self-Propelled Artillery', 'Soviet Union', 'Cold War', '60 km/h', '500 km', '5', '42 tons',
    '152mm 2A64 howitzer, 12.7mm NSVT',
    'The 2S19 Msta-S is the main heavy self-propelled howitzer of the Russian Army, built on a hull that combines T-72 and T-80 components.',
    '2S19 Msta'),
  v('2S3 Akatsiya', 'Self-Propelled Artillery', 'Soviet Union', 'Cold War', '60 km/h', '500 km', '4', '27.5 tons',
    '152mm 2A33 howitzer, 7.62mm PKT',
    'The 2S3 Akatsiya was the Soviet answer to the M109 and remains in service across many former Warsaw Pact armies.',
    '2S3 Akatsiya'),
  v('AS-90', 'Self-Propelled Artillery', 'United Kingdom', 'Modern', '55 km/h', '370 km', '5', '45 tons',
    '155mm L/39 howitzer, 12.7mm HMG',
    'The AS-90 was the British Army\'s standard self-propelled gun from 1993 until it began being replaced, with many units donated to Ukraine.',
    'AS-90'),
  v('Archer', 'Self-Propelled Artillery', 'Sweden', 'Modern', '70 km/h', '500 km', '4', '33.5 tons',
    '155mm L/52 FH77BW howitzer, 12.7mm RWS',
    'Archer is a fully automated wheeled howitzer that can fire its first round within 30 seconds of stopping and be moving again moments later.',
    'Archer artillery system'),
  v('M7 Priest', 'Self-Propelled Artillery', 'USA', 'WWII', '38 km/h', '190 km', '7', '22.9 tons',
    '105mm M2A1 howitzer, 12.7mm M2',
    'The M7 Priest got its name from its pulpit-like machine-gun ring and provided mobile artillery support to Allied armoured divisions.',
    'M7 Priest'),
  v('Wespe', 'Self-Propelled Artillery', 'Germany', 'WWII', '40 km/h', '220 km', '5', '11 tons',
    '105mm leFH 18/2 howitzer',
    'The Wespe mounted a 105mm howitzer on an obsolete Panzer II chassis, giving panzer divisions mobile light artillery.',
    'Wespe'),
  v('M142 HIMARS', 'Rocket Artillery', 'USA', 'Modern', '85 km/h', '480 km', '3', '16.25 tons',
    '6x GMLRS guided rockets or 1x ATACMS missile',
    'HIMARS is a wheeled rocket launcher that fires precision-guided rockets and relocates within minutes, making it hard to counter.',
    'M142 HIMARS'),
  v('M270 MLRS', 'Rocket Artillery', 'USA', 'Cold War', '64 km/h', '480 km', '3', '24.9 tons',
    '12x 227mm rockets or 2x ATACMS missiles',
    'The M270 is a tracked multiple rocket launcher that can saturate a large area or fire precision rockets, operated by many NATO armies.',
    'M270 Multiple Launch Rocket System'),
  v('BM-21 Grad', 'Rocket Artillery', 'Soviet Union', 'Cold War', '75 km/h', '750 km', '3', '13.7 tons',
    '40x 122mm rockets',
    'The BM-21 Grad is the world\'s most widespread multiple rocket launcher; it can fire all 40 rockets in about 20 seconds.',
    'BM-21 Grad'),
  v('BM-13 Katyusha', 'Rocket Artillery', 'Soviet Union', 'WWII', '', '', '5–7', '6.2 tons',
    '16x 132mm M-13 rockets',
    'The Katyusha rocket launcher was feared for its sudden, howling salvos. German troops nicknamed it "Stalin\'s organ".',
    'Katyusha rocket launcher'),

  // ---- Reconnaissance ----
  v('LAV-25', 'Reconnaissance', 'USA', 'Cold War', '100 km/h', '660 km', '3 + 6 scouts', '12.8 tons',
    '25mm M242 Bushmaster, 2x 7.62mm M240',
    'The LAV-25 is the US Marine Corps\' amphibious light armoured reconnaissance vehicle, prized for speed and range.',
    'LAV-25'),
  v('FV107 Scimitar', 'Reconnaissance', 'United Kingdom', 'Cold War', '80 km/h', '450 km', '3', '7.8 tons',
    '30mm L21 RARDEN cannon, 7.62mm L37A1',
    'The Scimitar is a tracked reconnaissance vehicle from the CVR(T) family, used by British reconnaissance units for decades.',
    'FV107 Scimitar'),
  v('Fennek', 'Reconnaissance', 'Germany', 'Modern', '115 km/h', '1,000 km', '3', '10 tons',
    '7.62mm MG3, 12.7mm HMG or 40mm GMW',
    'The Fennek is a low-profile scout car with a mast-mounted sensor suite that can observe targets from long range while staying hidden.',
    'Fennek'),
  v('BRDM-2', 'Reconnaissance', 'Soviet Union', 'Cold War', '95 km/h', '750 km', '4', '7 tons',
    '14.5mm KPVT, 7.62mm PKT',
    'The BRDM-2 is an amphibious scout car with retractable belly wheels for crossing trenches, and it has been exported to dozens of countries.',
    'BRDM-2'),
  v('AMX-10 RC', 'Reconnaissance', 'France', 'Cold War', '85 km/h', '800 km', '4', '15.9 tons',
    '105mm F2 gun, 7.62mm coax',
    'The AMX-10 RC is a six-wheeled armoured car with tank-like firepower, used for reconnaissance and fire support.',
    'AMX-10 RC'),
  v('EBRC Jaguar', 'Reconnaissance', 'France', 'Modern', '90 km/h', '800 km', '3', '25 tons',
    '40mm CTA40 cannon, 7.62mm RWS, 2x Akeron MP missiles',
    'The Jaguar replaces the AMX-10 RC as part of France\'s SCORPION programme, networked with other vehicles to share targets in real time.',
    'EBRC Jaguar'),
  v('Sd.Kfz. 234/2 Puma', 'Reconnaissance', 'Germany', 'WWII', '85 km/h', '900 km', '4', '11.7 tons',
    '50mm KwK 39/1 gun, 7.92mm MG 42',
    'The Puma was an eight-wheeled armoured car with an exceptional range for WWII and a 50mm gun that let it fight its way out of trouble.',
    'Sd.Kfz. 234'),
  v('M8 Greyhound', 'Reconnaissance', 'USA', 'WWII', '90 km/h', '560 km', '4', '7.8 tons',
    '37mm M6 gun, 12.7mm M2, 7.62mm M1919',
    'The M8 Greyhound was a fast six-wheeled armoured car used by US cavalry reconnaissance units in Europe and the Pacific.',
    'M8 Greyhound'),

  // ---- Air defense ----
  v('Flakpanzer Gepard', 'Air Defense', 'West Germany', 'Cold War', '65 km/h', '550 km', '3', '47.5 tons',
    '2x 35mm Oerlikon KDA autocannons',
    'The Gepard uses twin radar-guided 35mm guns on a Leopard 1 hull, and it has recently proved effective against drones and cruise missiles.',
    'Flakpanzer Gepard'),
  v('ZSU-23-4 Shilka', 'Air Defense', 'Soviet Union', 'Cold War', '50 km/h', '450 km', '4', '19 tons',
    '4x 23mm 2A7 autocannons',
    'The Shilka pairs four radar-guided 23mm cannons, and it was feared by low-flying aircraft in Vietnam and the Middle East.',
    'ZSU-23-4 Shilka'),
  v('2K22 Tunguska', 'Air Defense', 'Soviet Union', 'Cold War', '65 km/h', '500 km', '4', '34 tons',
    '2x 30mm 2A38M autocannons, 8x 9M311 SAM',
    'The Tunguska combines guns and missiles on one tracked chassis to protect armoured columns from helicopters and aircraft.',
    '2K22 Tunguska'),
  v('Pantsir-S1', 'Air Defense', 'Russia', 'Modern', '90 km/h', '500 km', '3', '30 tons',
    '2x 30mm 2A38M autocannons, 12x 57E6 SAM',
    'The Pantsir-S1 is a truck-mounted gun-missile system that provides short-range defence against aircraft, drones, and precision munitions.',
    'Pantsir missile system'),
  v('9K330 Tor', 'Air Defense', 'Soviet Union', 'Cold War', '65 km/h', '500 km', '3', '34 tons',
    '8x 9M330 surface-to-air missiles',
    'The Tor is an all-weather, short-range missile system that can detect and engage several targets while on the move.',
    'Tor missile system'),
  v('AN/TWQ-1 Avenger', 'Air Defense', 'USA', 'Cold War', '89 km/h', '443 km', '2', '3.9 tons',
    '8x FIM-92 Stinger missiles, 12.7mm M3P',
    'The Avenger mounts a turret with eight Stinger missiles on a Humvee to protect troops from low-flying aircraft and drones.',
    'AN/TWQ-1 Avenger'),
  v('Stryker M-SHORAD', 'Air Defense', 'USA', 'Modern', '97 km/h', '483 km', '4', '20 tons',
    '30mm XM914 cannon, Stinger and Hellfire missiles, 7.62mm MG',
    'M-SHORAD restores short-range air defence to US armoured units, mounting a gun and missile turret on the Stryker chassis.',
    'File:M-SHORAD Stryker.jpg'),
  v('Flakpanzer IV Wirbelwind', 'Air Defense', 'Germany', 'WWII', '38 km/h', '200 km', '5', '22 tons',
    '4x 20mm Flak 38 autocannons',
    'The Wirbelwind ("Whirlwind") put a quad 20mm flak turret on a Panzer IV chassis to protect armoured units from Allied fighter-bombers.',
    'File:Wirbelwind CFB Borden 4.jpg'),
  v('M16 MGMC', 'Air Defense', 'USA', 'WWII', '72 km/h', '280 km', '5', '9 tons',
    '4x 12.7mm M2 (Maxson M45 quadmount)',
    'The M16 half-track carried four .50-calibre machine guns and was nicknamed the "meat chopper" for its devastating ground-attack use.',
    'M16 multiple gun motor carriage'),

  // ---- Utility vehicles ----
  v('Willys MB Jeep', 'Utility Vehicle', 'USA', 'WWII', '105 km/h', '480 km', '1–4', '1 ton',
    '7.62mm M1919 on pintle mount (optional)',
    'The Willys MB Jeep became a WWII icon. It could carry troops, tow guns, or serve as an ambulance, and it went on to inspire civilian 4x4s.',
    'Willys MB'),
  v('Volkswagen Kübelwagen', 'Utility Vehicle', 'Germany', 'WWII', '80 km/h', '450 km', '1–4', '0.73 tons',
    '7.92mm MG 34 (optional)',
    'The Kübelwagen was a light, air-cooled military car based on the Volkswagen Beetle; its flat underside let it slide over mud and sand.',
    'Volkswagen Kübelwagen'),
  v('HMMWV (Humvee)', 'Utility Vehicle', 'USA', 'Cold War', '113 km/h', '480 km', '1–4', '2.4 tons',
    '12.7mm M2, 40mm Mk19 or 7.62mm M240 (variant dependent)',
    'The Humvee replaced the Jeep as the US military\'s light utility vehicle in the 1980s and has been built in dozens of configurations.',
    'Humvee'),
  v('Oshkosh JLTV', 'Utility Vehicle', 'USA', 'Modern', '113 km/h', '480 km', '2–4', '6.4 tons',
    '12.7mm M2, 40mm Mk19 or 7.62mm M240 (CROWS)',
    'The Joint Light Tactical Vehicle is replacing the Humvee, offering MRAP-level blast protection with far better off-road mobility.',
    'Oshkosh L-ATV'),
  v('GAZ Tigr', 'Utility Vehicle', 'Russia', 'Modern', '140 km/h', '1,000 km', '2 + 9 passengers', '7.2 tons',
    '7.62mm PKP or 12.7mm Kord (variant dependent)',
    'The GAZ Tigr is a Russian high-mobility armoured utility vehicle widely used by the army, police, and special forces.',
    'GAZ Tigr'),
]
